mnolms/mnolms/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('seis/', include('seisnet.urls', namespace='seis'))
]

mnolms/seisnet/urls.py
from django.urls import path

from dal import autocomplete

from . import views

# from equipment.models import DataloggerEntity

app_name = 'seis'

urlpatterns = [

    path('station', views.StationListView.as_view(), name='station_list'),
    path('station/add', views.station_add, name='station_add'),
    path('station/detail/<int:pk>', views.station_detail, name='station_detail'),
    # path('station/edit/<int:pk>', views.station_edit, name='station_edit'),

    # path('station/dataloggerentity-autocomplete',
    #      views.DataloggerEntityAutocomplete.as_view(),
    #      name='dataloggerentity-autocomplete'),
    # path('station/dataloggerentity-autocomplete/<int:fk>',
    #      views.DataloggerEntityAutocomplete.as_view(),
    #      name='dataloggerentity-autocomplete'),
    # path('station/sensorentity-autocomplete',
    #      views.SensorEntityAutocomplete.as_view(),
    #      name='sensorentity-autocomplete'),
    # path('station/sensorentity-autocomplete/<int:fk>',
    #      views.SensorEntityAutocomplete.as_view(),
    #      name='sensorentity-autocomplete'),

    path('station/seisentity-autocomplete',
         views.SeismologicalEquipmentEntityAutocomplete.as_view(),
         name='seisentity-autocomplete'),
    path('station/seisentity-autocomplete/<int:fk>',
         views.SeismologicalEquipmentEntityAutocomplete.as_view(),
         name='seisentity-autocomplete'),

    # path('net', views.network_list, name='network_list'),
    path('net', views.NetworkListView.as_view(), name='network_list'),
    path('net/add', views.network_add, name='network_add'),
    # path('net/detail/<int:pk>', views.network_detail, name='network_detail'),
    path('net/detail/<int:pk>', views.NetworkDetailView.as_view(), name='network_detail'),
    path('net/edit/<int:pk>', views.network_edit, name='network_edit'),

    path('station/test', views.test, name='test'),

]

mnolms/seisnet/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType

from equipment.models import SeismologicalEquipmentEntity


class Network(models.Model):
    """
    台网信息
    """
    NET_STATUS = (
        (0, '运行'),
        (1, '测试'),
        (2, '下线')
    )
    code = models.CharField(max_length=10, unique=True, verbose_name="台网代码")
    name = models.CharField(max_length=64, verbose_name="台网名称")
    start_time = models.DateField("开始时间", null=True, blank=True)
    end_time = models.DateField("结束时间", null=True, blank=True)
    min_longitude = models.FloatField(null=True, blank=True, verbose_name="台网最小经度")
    max_longitude = models.FloatField(null=True, blank=True, verbose_name="台网最大经度")
    min_latitude = models.FloatField(null=True, blank=True, verbose_name="台网最小纬度")
    max_latitude = models.FloatField(null=True, blank=True, verbose_name="台网最大纬度")
    status = models.PositiveSmallIntegerField(choices=NET_STATUS, default=0, verbose_name="台网状体")
    describe = models.TextField(blank=True, null=True, verbose_name="台网描述")

    c_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    m_time = models.DateTimeField(auto_now=True, verbose_name="更新日期")

    class Meta:
        verbose_name = "台网信息"
        verbose_name_plural = "台网信息"

    def __str__(self):
        return "{code}-{name}".format(code=self.code, name=self.name)


class Station(models.Model):
    """
    台站信息
    """
    STATION_STATUS = (
        (0, '运行'),
        (1, '测试'),
        (2, '故障'),
        (3, '下线')
    )
    code = models.CharField(max_length=10, unique=True, verbose_name="台站代码")
    en_name = models.CharField(max_length=64, verbose_name="台站名称(英文)")
    zh_name = models.CharField(max_length=64, verbose_name="台站名称(中文)")
    longitude = models.FloatField(verbose_name="台站经度")
    latitude = models.FloatField(verbose_name="台站纬度")
    altitude = models.FloatField(verbose_name="台站高程")
    status = models.PositiveSmallIntegerField(
        choices=STATION_STATUS,
        default=0,
        verbose_name="台站状态")
    describe = models.TextField(null=True, blank=True, verbose_name="台站描述")
    location = models.TextField(null=True, blank=True, verbose_name="位置描述")
    network = models.ForeignKey(
        'Network',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="所属台网")

    c_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    m_time = models.DateTimeField(auto_now=True, verbose_name="更新日期")

    class Meta:
        verbose_name = "台站信息"
        verbose_name_plural = "台站信息"

    def __str__(self):
        return "{code}-{zh_name}({en_name})".format(
            code=self.code,
            zh_name=self.zh_name,
            en_name=self.en_name)

    @property
    def seismological_equipments(self):
        instance = self
        qs = SeismologicalEquipmentEntity.objects.filter_by_instance(instance)
        return qs

    # @property
    # def dataloggers(self):
    #     instance = self
    #     qs = DataloggerEntity.objects.filter(station=instance)
    #     return qs
    #
    # @property
    # def sensors(self):
    #     instance = self
    #     qs = SensorEntity.objects.filter(station=instance)
    #     # qs = SensorEntity.objects.filter_by_instance(instance)
    #     return qs


# class EquipmentItem(models.Model):
#     """
#     每个台站的设备清单
#     """
#     station = models.ForeignKey(
#         Station,
#         null=True,
#         blank=True,
#         on_delete=models.SET_NULL,
#         related_name='设备清单')
#     equipment = models.ForeignKey(
#         'equipment.Equipment',
#         null=True,
#         blank=True,
#         on_delete=models.SET_NULL)
#     quantity = models.PositiveIntegerField(default=1)
#
#     def __str__(self):
#         return '{id}'.format(id=self.id)


class Caretaker(models.Model):
    """
    看护人信息
    """
    CARETAKE_STATUS = (
        (1, '在看护'),
        (2, '曾看护'),
        (3, '中断'),
        (4, '其它')
    )

    name = models.CharField(max_length=20, verbose_name="姓名")
    gender = models.PositiveSmallIntegerField(choices=((0, '男'), (1, '女')), default=0, verbose_name="性别")
    id_card = models.CharField(max_length=64, verbose_name="身份证号")
    address = models.CharField(max_length=256, verbose_name="地址")

    status = models.PositiveSmallIntegerField(choices=CARETAKE_STATUS, verbose_name="状态")

    start_time = models.DateField(null=True, blank=True, verbose_name="开始时间")
    end_time = models.DateField(null=True, blank=True, verbose_name="结束时间")

    remark = models.CharField(max_length=256, blank=True, null=True, verbose_name="备注")

    care_station = models.ForeignKey('Station', on_delete=models.DO_NOTHING,
                                     verbose_name="看护的台站")
    is_main = models.BooleanField(default=True, verbose_name="主要看护人")

    class Meta:
        verbose_name = "看护人信息"
        verbose_name_plural = "看护人信息"

    def __str__(self):
        return "{name}({id_card})".format(name=self.name, id_card=self.id_card)


class Phone(models.Model):
    """
    电话号码
    """
    number = models.CharField(max_length=20, verbose_name="号码")
    owner = models.ForeignKey(
        'Caretaker',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name="所有者")

    def __str__(self):
        return self.number


class CarePayment(models.Model):
    """
    看护费信息
    """
    unit_price = models.FloatField(default=150.00, verbose_name="看护费(元/月)")
    start_pay = models.DateField(verbose_name="支付开始日期(年-月)")
    end_pay = models.DateField(verbose_name="支付截止日期(年-月)")

    pay_date = models.DateField(verbose_name="支付日期")

    caretaker = models.ForeignKey("Caretaker", on_delete=models.DO_NOTHING,
                                  verbose_name="看护人")

    def pay_months(self):
        months = int(self.end_pay.month - self.start_pay.month + 1)
        return months if months > 0 else months+12

    class Meta:
        verbose_name = "看护费支付信息"
        verbose_name_plural = "看护费支付信息"

    def __str__(self):
        return "{unit_price} - {pay_months} - {end_pay}".format(
            unit_price=self.unit_price,
            pay_months=self.pay_months,
            end_pay=self.end_pay
        )

mnolms/seisnet/forms.py
from django import forms
from django.utils.encoding import force_text
from django.urls import reverse_lazy
from django.contrib.admin import StackedInline

from bootstrap_datepicker.widgets import DatePicker
from dal import autocomplete

from .models import Network, Station
# from equipment.models import DataloggerEntity, SensorEntity, EquimpmentItem
from equipment.models import (
    Equipment,
    PowerSupplyModel,
    NetworkDeviceModel,
    SeismologicalEquipmentEntity,
    # EquimpmentItem,
    PowerSupplyModelItem,
    NetworkDeviceModelItem,
)


class NetworkForm(forms.ModelForm):

    class Meta:
        model = Network
        fields = ('code', 'name', 'start_time', 'end_time', 'status', 'describe')

    start_time = forms.DateField(
        label="开始时间",
        widget=DatePicker(
            attrs={'class': 'test-123', },
            options={
                "format": "yyyy-mm-dd",
                "autoclose": True,
            },
        ),
        required=False
    )

    end_time = forms.DateField(
        label="结束时间",
        required=False,
        widget=DatePicker(
            options={
                "format": "yyyy-mm-dd",
                "autoclose": True
            },
        )
    )


class StationForm(forms.ModelForm):

    class Meta:
        model = Station
        fields = ('network', 'code',
                  'en_name', 'zh_name',
                  'longitude', 'latitude',
                  'altitude', 'status',
                  'seismological_equipments',
                  'describe', 'location',
                  )

    seismological_equipments = forms.ModelMultipleChoiceField(
        label='测震仪器列表',
        queryset=SeismologicalEquipmentEntity.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2Multiple(
            url=reverse_lazy('seis:seisentity-autocomplete')
        )
    )


# class SeismologicalEquipmentEntityForm(forms.ModelForm):
#     class Meta:
#         model = SeismologicalEquipmentEntity
#         fields = ('id',)
#
#     sseismological_equipments = forms.ModelMultipleChoiceField(
#         label='测震设备列表',
#
#         queryset=SeismologicalEquipmentEntity.objects.all(),
#         required=False,
#         widget=autocomplete.ModelSelect2Multiple(
#             url=reverse_lazy('seis:seisentity-autocomplete')
#         )
#     )


class PowerSupplyItemForm(forms.ModelForm):
    # def __init__(self, station, *args, **kwargs):
    #     self.station = station
    #     super(PowerSupplyItemForm, self).__init__(*args, **kwargs)

    # equipment = forms.ModelChoiceField(
    #     label='供电设备列表',
    #     queryset=Equipment.objects.instance_of(PowerSupplyModel),
    #     required=False,
    # )

    class Meta:
        model = PowerSupplyModelItem
        fields = ('equipment', 'quantity')
        labels = {
            'equipment': '供电设备',
            'quantity': '数量',
        }
        widgets = {
            'equipment': forms.Select(),
        }


class NetworkDeviceItemForm(forms.ModelForm):
    # def __init__(self, station, *args, **kwargs):
    #     self.station = station
    #     super(NetworkDeviceItemForm, self).__init__(*args, **kwargs)

    # equipment = forms.ModelChoiceField(
    #     label='网络设备列表',
    #     queryset=Equipment.objects.instance_of(NetworkDeviceModel),
    #     required=False,
    # )

    class Meta:
        model = NetworkDeviceModelItem
        fields = ('equipment', 'quantity')
        labels = {
            'equipment': '网络设备',
            'quantity': '数量',
        }
        widgets = {
            'equipment': forms.Select(),
        }


class SeismologicalEquipmentEntityForm(forms.Form):
    seismological = forms.ModelChoiceField(
        label='测震仪器列表',
        queryset=SeismologicalEquipmentEntity.objects.all(),
    )

# class NetworkDeviceItemForm(forms.ModelForm):
#     class Meta:
#         model = NetworkDeviceItem
#         fields = ('network_device', 'quantity',)
#
#
#     def cleaned_data(self):
#         return True

mnolms/seisnet/templates/seisnet/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>台网运维日志管理系统</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha256-rByPlHULObEjJ6XQxW/flG2r+22R5dKiAoef+aXWfik=" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css" integrity="sha256-5ad0JyXou2Iz0pLxE+pMd3k/PliXbkc65CO5mavx8s8=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js" integrity="sha256-urCxMaTtyuE8UK5XeVYuQbm/MhnXflqZ/B9AOkyTguo=" crossorigin="anonymous"></script>
</head>
<body>
<div class="page-header">
    <h1><a href="/">台网运维日志管理系统</a></h1>
</div>
<div class="content container">
    <div class="row">
        <div class="col-md-10">
            {% block content %}
            {% endblock %}
        </div>

    </div>
</div>

</body>
</html>

mnolms/seisnet/templates/seisnet/network_detail.html
{% extends 'seisnet/base.html' %}


{% block content %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="9" scope="col"><h1 align="center">台网详情</h1></th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th> 台网代码 </td>
                <td>{{ network.code }}</td>
            </tr>
            <tr>
                <th>台网名称</td>
                <td>{{ network.name }}</td>
            </tr>
            <tr>
                <th>开始时间</td>
                <td>{{ network.start_time | date:"Y-m" }}</td>
            </tr>
            <tr>
                <th>结束时间</td>
                <td>{{ network.end_time | date:"Y-m"}}</td>
            </tr>
            <tr>
                <th>监测范围</td>
                <td>
                {{ network.min_latitude }}/
                {{ network.max_latitude }}/
                {{ network.min_longitude }}/
                {{ network.max_longitude }}
                </td>
            </tr>
            <tr>
                <th>台网状态</td>
                <td>{{ network.get_status_display }}</td>
            </tr>
            <tr>
                <th>台网描述</th>
                <td>{{ network.describe | default:"--" }}</td>
            </tr>
        </tbody>

    </table>
    <a href="{% url 'seis:network_edit' pk=network.pk %}">编辑</a>

{% endblock %}

mnolms/seisnet/templates/seisnet/network_edit.html
{% extends 'seisnet/base.html' %}
{% load bootstrap %}

{% block content %}
{#    <div class="col-md-6">#}
    <form method="POST", role="form" class="form-horizontal">
        {% if form.instance.pk %}
            <legend>修改台网信息</legend>
        {% else %}
            <legend>新增台网信息</legend>
        {% endif %}
        {{ form | bootstrap_horizontal }}
        {% csrf_token %}
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
            <button type="submit" class="save btn btn-primary">保存</button>
            </div>
        </div>
    </form>
{#    </div>#}

{% endblock %}

mnolms/seisnet/templates/seisnet/network_list.html
{% extends 'seisnet/base.html' %}


{% block content %}

    <table class="table table-hover">
        <thead>
            <tr>
                <th colspan="9" scope="col"><h1 align="center">台网列表</h1></th>
            </tr>
            <tr>
                <th scope="col">#</th>
                <th scope="col">台网代码</th>
                <th scope="col">台网名</th>
                <th scope="col">开始时间</th>
                <th scope="col">结束时间</th>
                <th scope="col">台网监测范围</th>
                <th scope="col">台站数</th>
                <th scope="col">状态</th>
                <th scope="col">操作</th>
            </tr>
        </thead>

        {% for network in networks %}
        <tbody>
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                    <a href="{% url 'seis:network_detail' pk=network.pk %}">{{ network.code }}</a>
                </td>
                <td>{{ network.name }}</td>
                <td>{{ network.start_time | date:"Y-m" }}</td>
                <td>{{ network.end_time | date:"Y-m"}}</td>
                <td>
                    {{ network.min_latitude }}/
                    {{ network.max_latitude }}/
                    {{ network.min_longitude }}/
                    {{ network.max_longitude }}
                </td>
                <td>
                    {{ network.station_set.count }}
                </td>
                <td>{{ network.get_status_display }}</td>
                <td>
                    <a href="{% url 'seis:network_edit' pk=network.pk %}">编辑</a>
                </td>
            </tr>
        </tbody>
        {% endfor %}

    </table>

{% endblock %}

mnolms/seisnet/templates/seisnet/station_detail.html
{% extends 'seisnet/base.html' %}


{% block content %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="9" scope="col"><h1 align="center">台站详情</h1></th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th> 所属台网 </th>
                <td>{{ station.network }}</td>
            </tr>
            <tr>
                <th> 台站代码 </th>
                <td>{{ station.code }}</td>
            </tr>
            <tr>
                <th>台站名称(中文)</th>
                <td>{{ station.zh_name }}</td>
            </tr>
            <tr>
                <th>台站名称(英文)</th>
                <td>{{ station.en_name }}</td>
            </tr>
            <tr>
                <th>台站经度</th>
                <td>{{ station.longitude }}</td>
            </tr>
            <tr>
                <th>台站纬度</th>
                <td>{{ station.latitude }}</td>
            </tr>
            <tr>
                <th>测震设备列表</th>
                <td>
                <ul>
                    {% for seismological in station.seismological_equipments %}
                        <li> {{ seismological }} </li>
                    {% endfor %}
                </ul>
                </td>
            </tr>
            <tr>
                <th>台站状态</th>
                <td>{{ station.get_status_display }}</td>
            </tr>
            <tr>
                <th>台站位置描述</th>
                <td>{{ station.location | default:"--" }}</td>
            </tr>
            <tr>
                <th>台站描述</th>
                <td>{{ station.describe | default:"--" }}</td>
            </tr>
        </tbody>

    </table>
    <a href="{% url 'seis:station_edit' pk=station.pk %}">编辑</a>

{% endblock %}

mnolms/seisnet/templates/seisnet/station_edit.html
{% extends 'seisnet/base.html' %}
{% load bootstrap %}
{% load static %}

{% block content %}
    <form method="POST", role="form" class="form-horizontal">
{#        {% crispy station_form formset %}#}
        {% if station_form.instance.pk %}
            <legend>修改台站信息</legend>
        {% else %}
            <legend>新增台站信息</legend>
        {% endif %}

        {{ station_form | bootstrap_horizontal }}

        {{ powersupply_item_form_set.management_form }}
        {{ powersupply_item_form_set | bootstrap_horizontal }}

        {{ network_device_item_form_set | bootstrap_horizontal }}
        {{ network_device_item_form_set.management_form }}
        {% csrf_token %}
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <button type="submit" class="save btn btn-primary">保存</button>
            </div>
        </div>
    </form>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {{ station_form.media }}

{% endblock %}

mnolms/seisnet/templates/seisnet/station_list.html
{% extends 'seisnet/base.html' %}


{% block content %}

    <table class="table table-hover">
        <thead>
            <tr>
                <th colspan="9" scope="col"><h1 align="center">台站列表</h1></th>
            </tr>
            <tr>
                <th scope="col">#</th>
                <th scope="col">台站代码</th>
                <th scope="col">台站名(中文)</th>
                <th scope="col">台站名(英文)</th>
                <th scope="col">台站经度</th>
                <th scope="col">台站纬度</th>
                <th scope="col">台站高程</th>
{#                <th scope="col">开始时间</th>#}
{#                <th scope="col">结束时间</th>#}
                <th scope="col">状态</th>
                <th scope="col">操作</th>
            </tr>
        </thead>

        {% for station in stations %}
        <tbody>
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                    <a href="{% url 'seis:station_detail' pk=station.pk %}">{{ station.code }}</a>
                </td>
                <td>{{ station.zh_name }}</td>
                <td>{{ station.en_name }}</td>
                <td>{{ station.longitude }}</td>
                <td>{{ station.latitude }}</td>
                <td>{{ station.altitude }}</td>
                <td>{{ station.get_status_display }}</td>
                <td>
                    <a href="{% url 'seis:station_edit' pk=station.pk %}">编辑</a>
                </td>
            </tr>
        </tbody>
        {% endfor %}

    </table>

{% endblock %}

mnolms/seisnet/templates/seisnet/test.html
{% extends 'seisnet/base.html' %}
{% load bootstrap %}
{% load static %}

{% block content %}
    <form method="POST", role="form" class="form-horizontal">
        {{ form | bootstrap_horizontal }}
        {% csrf_token %}
    </form>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {{ form.media }}

{% endblock %}